### ISSUE TITLE
Underscore instead of dash

### ISSUE THREAD

**Issue by gcelano** [latin-language-toolkit/arethusa#682] opened 2015-05-11 11:36 UTC
In the @postag attribute the last value is saved as underscore instead of dash.

**Comment by balmas** [comment] 2015-05-11 12:08
Dupe of #673

**Closed by balmas** 2015-05-11 12:08 UTC

**Comment by Masoumeh** [comment] 2015-06-09 06:08
It seems the problem comes from an underscore assigned to the postag in morph.js.
I've created a pull request.
